import { ArrowLeft, Bot, AlertTriangle, CheckCircle2 } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";

export default function AIDisclaimer() {
  return (
    <div className="min-h-screen bg-background py-8 px-4">
      <div className="container mx-auto max-w-4xl">
        <Link href="/">
          <Button variant="ghost" size="sm" className="mb-6" data-testid="button-back-home">
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Home
          </Button>
        </Link>

        <Card>
          <CardHeader>
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-xl bg-primary/10">
                <Bot className="h-6 w-6 text-primary" />
              </div>
              <div>
                <CardTitle className="text-3xl font-heading">AI Disclaimer</CardTitle>
                <p className="text-sm text-muted-foreground">Last updated: January 2026</p>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <ScrollArea className="h-[calc(100vh-280px)]">
              <div className="prose prose-sm dark:prose-invert max-w-none space-y-6">
                <section>
                  <div className="p-4 rounded-xl bg-chart-4/10 border border-chart-4/20">
                    <div className="flex items-start gap-3">
                      <AlertTriangle className="h-5 w-5 text-chart-4 shrink-0 mt-0.5" />
                      <div>
                        <p className="font-semibold text-foreground mb-1">Important Notice</p>
                        <p className="text-sm text-muted-foreground">
                          InterviewPro uses artificial intelligence to provide career preparation 
                          assistance. Please read this disclaimer carefully to understand the 
                          nature and limitations of AI-generated content.
                        </p>
                      </div>
                    </div>
                  </div>
                </section>

                <section>
                  <h2>1. Nature of AI-Generated Content</h2>
                  <p>
                    InterviewPro uses advanced AI technology to provide:
                  </p>
                  <ul>
                    <li>CV analysis and optimization suggestions</li>
                    <li>Interview questions tailored to your experience and target role</li>
                    <li>Performance feedback and scoring</li>
                    <li>Improvement recommendations</li>
                  </ul>
                  <p>
                    All of this content is generated by artificial intelligence algorithms 
                    and should be understood as such.
                  </p>
                </section>

                <section>
                  <h2>2. Advisory Nature of Feedback</h2>
                  <div className="p-4 rounded-xl bg-muted/50 space-y-3">
                    <div className="flex items-start gap-3">
                      <CheckCircle2 className="h-5 w-5 text-chart-2 shrink-0 mt-0.5" />
                      <p className="text-sm">
                        <strong>AI feedback is advisory only.</strong> It is not professional 
                        career counseling, hiring advice, or a guarantee of any outcome.
                      </p>
                    </div>
                    <div className="flex items-start gap-3">
                      <CheckCircle2 className="h-5 w-5 text-chart-2 shrink-0 mt-0.5" />
                      <p className="text-sm">
                        <strong>You are in control.</strong> You remain fully responsible for 
                        your CV content, interview responses, and career decisions.
                      </p>
                    </div>
                    <div className="flex items-start gap-3">
                      <CheckCircle2 className="h-5 w-5 text-chart-2 shrink-0 mt-0.5" />
                      <p className="text-sm">
                        <strong>Review all suggestions.</strong> Always review and critically 
                        evaluate AI suggestions before implementing them.
                      </p>
                    </div>
                  </div>
                </section>

                <section>
                  <h2>3. Limitations of AI</h2>
                  <p>
                    While our AI is designed to be helpful and accurate, it has limitations:
                  </p>
                  <ul>
                    <li>
                      <strong>Imperfect results:</strong> AI may occasionally produce suggestions 
                      that are not optimal for your specific situation.
                    </li>
                    <li>
                      <strong>Incomplete analysis:</strong> AI cannot fully understand all nuances 
                      of your career history, industry specifics, or personal circumstances.
                    </li>
                    <li>
                      <strong>Potential inaccuracies:</strong> AI-generated content may sometimes 
                      contain errors or suggestions that are not applicable.
                    </li>
                    <li>
                      <strong>Evolving technology:</strong> AI capabilities are continuously 
                      improving, but current limitations exist.
                    </li>
                    <li>
                      <strong>Not real interview:</strong> Mock interviews cannot perfectly 
                      replicate real interview conditions or interviewer behavior.
                    </li>
                  </ul>
                </section>

                <section>
                  <h2>4. No Employment Guarantee</h2>
                  <p>
                    <strong>InterviewPro does not guarantee employment, interview invitations, 
                    or job offers.</strong> Your success in the job market depends on many 
                    factors beyond our control, including:
                  </p>
                  <ul>
                    <li>Market conditions and competition</li>
                    <li>Employer-specific requirements and preferences</li>
                    <li>Your qualifications and experience</li>
                    <li>The quality of your actual interview performance</li>
                    <li>Factors specific to each opportunity</li>
                  </ul>
                </section>

                <section>
                  <h2>5. User Responsibility</h2>
                  <p>By using InterviewPro, you acknowledge that:</p>
                  <ul>
                    <li>You are responsible for reviewing and validating all AI suggestions</li>
                    <li>You make your own decisions about your CV content and interview approach</li>
                    <li>You understand that AI feedback is one of many inputs to consider</li>
                    <li>You should seek professional career advice if needed</li>
                    <li>You will not hold InterviewPro liable for employment outcomes</li>
                  </ul>
                </section>

                <section>
                  <h2>6. Scoring and Evaluation</h2>
                  <p>
                    Performance scores and evaluations provided by our AI are:
                  </p>
                  <ul>
                    <li>Based on algorithmic analysis of your responses</li>
                    <li>Designed to help you identify areas for improvement</li>
                    <li>Not a definitive measure of your interview readiness</li>
                    <li>Subject to the limitations inherent in AI evaluation</li>
                  </ul>
                  <p>
                    Real interviewers may evaluate you differently based on their own 
                    criteria, preferences, and the specific role requirements.
                  </p>
                </section>

                <section>
                  <h2>7. Continuous Improvement</h2>
                  <p>
                    We are continuously working to improve our AI systems. If you 
                    encounter issues or have feedback about AI-generated content, 
                    please let us know through our support channels. Your feedback 
                    helps us make the platform better for everyone.
                  </p>
                </section>

                <section>
                  <h2>8. Questions</h2>
                  <p>
                    If you have questions about our AI technology or this disclaimer, 
                    please contact us through the platform.
                  </p>
                </section>
              </div>
            </ScrollArea>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
